# Generated by Django 4.0 on 2023-11-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profiles/user1.png', upload_to='profiles'),
        ),
    ]
