# Generated by Django 4.0 on 2023-11-01 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('mychat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamptime', models.DateTimeField(auto_now_add=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_from', to='account.customusers')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_to', to='account.customusers')),
            ],
        ),
    ]
