# Generated by Django 4.0 on 2023-11-03 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('mychat', '0003_messages_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='firstUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='account.customusers'),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='secondUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='account.customusers'),
        ),
    ]
